services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: company_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  # this line does the magic
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    env_file: .env
    entrypoint: /opt/airflow/entrypoint.sh
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://etl_user:securepassword@postgres/company_db
      - PYTHONPATH=/opt/project
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - .:/opt/project
    ports:
      - "8080:8080"


  fastapi:
    build:
      context: .
      dockerfile: ./fastapi_service/Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  postgres_data:
